openapi: 3.0.3
info:
  title: Dish et Ingredient - OAS - TD5
  description: Représentation en OAS des endpoints de Dsh et Ingredient
  version: 1.0.0

servers:
  - http://localhost:8080

paths:
  #Dish
  /dishes:
    get:
      summary: Get all dishes
      responses:
        '200':
          description: List of dishes
        '500':
          description: Internal server error

  /dishes/{id}/ingredients:
    put:
      summary: update ingredients of a dish
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          appication/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'
      responses:
        '200':
          description: Ingredient updated
        '400':
          description: Request body is required
        '404':
          description: Dish not found
        '500':
          description: Internal server error

    get:
      summary: Get ingredients of a dish with filter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: ingredientName
          in: query
          required: false
          schema:
            type: string
        - name: ingredientPriceAround
          in: query
          required: false
          schema:
            type: number
            format: double
      responses:
        '200':
          description: List of ingredient
        '404':
          description: Dish not found
        '500':
          description: Internal server error

  #Ingredient
  /ingredients:
    get:
      summary: Get all ingredients
      responses:
        '200':
          description: List of ingredients
        '500':
          description: Internal server error

  /ingredients/{id}:
    get:
      summary: Get ingredient by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ingredient found
        '404':
          description: Ingredient not found
        '500':
          description: Internal server error

  /ingredients/{id}/stock:
    get:
      summary: Get ingredient stock at a given time and unit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: at
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: unit
          in: query
          required: true
          schema:
            type: string
            enum: [PCS, KG, L]
      responses:
        '200':
          description: stock value
        '400':
          description: Missing query parameters
        '404':
          description: Ingredient not found
        '500':
          description: Internal server error

components:
  schemas:

    Ingredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: double

    Dish:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'

    StockValue:
      type: object
      properties:
        value:
          type: number
          format: double
        unit:
          type: string
        date:
          type: string
          format: date-time